### ISSUE TITLE
Unable to run train.py

### ISSUE THREAD

**Issue by ongcj** [novioleo/FOTS#9]
Traceback (most recent call last):

  File "<ipython-input-1-b78358e603f3>", line 1, in <module>
    from model.model import *

  File "C:\Users\cheng\Desktop\FOTS-master\model\model.py", line 6, in <module>
    from utils.bbox import Toolbox

  File "C:\Users\cheng\Desktop\FOTS-master\utils\bbox.py", line 13, in <module>
    from . import lanms

  File "C:\Users\cheng\Desktop\FOTS-master\utils\lanms\__init__.py", line 7, in <module>
    if subprocess.call(['make', '-C', BASE_DIR]) != 0:  # return value

  File "C:\Users\cheng\Anaconda3\envs\FOTS\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Users\cheng\Anaconda3\envs\FOTS\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\cheng\Anaconda3\envs\FOTS\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "C:\Users\cheng\Anaconda3\envs\FOTS\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

Is there anything that i missed out? thanks.

**Comment by novioleo** [comment]
@ongcj i think you need install the make tools in windows.and add the path of `make` into your system path.
[ref: install make in windows](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows)

**Comment by RyanRTJJ** [comment]
@ongcj, how did you name your files? Somewhere in **data_loader/datautils.py**, in `def image_label(...)`, the first `try` chunk of code appends 'gt_' to the image file name. It might be why you can't find the file. Simply remove that appendage and try again.

**Comment by novioleo** [comment]
@RyanRTJJ he was just stuck with the make progress of lanms on windows....

**Comment by ongcj** [comment]
@novioleo @RyanRTJJ Hi and thanks. The above was resolved by installing make tools. Many thanks.

**Comment by novioleo** [comment]
feel free


 
---Original---
